import type { TagSection } from "@paperback/types";

export const DOMAIN = "https://niceoppai.net";

export const NICEOPPAI_TAGS: TagSection[] = [
  {
    id: "genres",
    title: "Genres",
    tags: [
      { id: "Action", title: "Action" },
      { id: "Adult", title: "Adult" },
      { id: "Adventure", title: "Adventure" },
      { id: "Comedy", title: "Comedy" },
      { id: "Comic", title: "Comic" },
      { id: "Cooking", title: "Cooking" },
      { id: "Croosover", title: "Croosover" },
      { id: "Dojin", title: "Dojin" },
      { id: "Doujinshi", title: "Doujinshi" },
      { id: "Drama", title: "Drama" },
      { id: "Ecchi", title: "Ecchi" },
      { id: "Fantasy", title: "Fantasy" },
      { id: "Gender%20Bender", title: "Gender Bender" },
      { id: "Genderswap", title: "Genderswap" },
      { id: "Grume", title: "Grume" },
      { id: "Harem", title: "Harem" },
      { id: "Hentai", title: "Hentai" },
      { id: "Historical", title: "Historical" },
      { id: "Horror", title: "Horror" },
      { id: "Indonesian", title: "Indonesian" },
      { id: "Isekai", title: "Isekai" },
      { id: "Josei", title: "Josei" },
      { id: "Lolicon", title: "Lolicon" },
      { id: "Manga", title: "Manga" },
      { id: "Manhua", title: "Manhua" },
      { id: "Manhwa", title: "Manhwa" },
      { id: "Manhwa%20Hentai", title: "Manhwa Hentai" },
      { id: "Martial%20Arts", title: "Martial Arts" },
      { id: "Mature", title: "Mature" },
      { id: "Mecha", title: "Mecha" },
      { id: "Military", title: "Military" },
      { id: "Mitsuru%20Inoue", title: "Mitsuru Inoue" },
      { id: "Murim", title: "Murim" },
      { id: "Music", title: "Music" },
      { id: "Mystery", title: "Mystery" },
      { id: "noval", title: "noval" },
      { id: "Novel", title: "Novel" },
      { id: "One%20Shot", title: "One Shot" },
      { id: "Philosophical", title: "Philosophical" },
      { id: "Post-Apocalyptic", title: "Post-Apocalyptic" },
      { id: "Psychological", title: "Psychological" },
      { id: "raw", title: "raw" },
      { id: "Reincarnation", title: "Reincarnation" },
      { id: "Revenge", title: "Revenge" },
      { id: "Romance", title: "Romance" },
      { id: "School%20Life", title: "School Life" },
      { id: "School-Life", title: "School-Life" },
      { id: "Sci%20Fi", title: "Sci Fi" },
      { id: "Sci-fi", title: "Sci-fi" },
      { id: "Second%20Life", title: "Second Life" },
      { id: "Seinen", title: "Seinen" },
      { id: "Shotacon", title: "Shotacon" },
      { id: "Shoujo", title: "Shoujo" },
      { id: "Shoujo%20Ai", title: "Shoujo Ai" },
      { id: "Shounen", title: "Shounen" },
      { id: "Shounen%20Ai", title: "Shounen Ai" },
      { id: "Slice%20of%20Life", title: "Slice of Life" },
      { id: "smut", title: "smut" },
      { id: "Sport", title: "Sport" },
      { id: "Sports", title: "Sports" },
      { id: "Superhero", title: "Superhero" },
      { id: "Supernatural", title: "Supernatural" },
      { id: "Survival", title: "Survival" },
      { id: "Thriller", title: "Thriller" },
      { id: "Tragedy", title: "Tragedy" },
      { id: "Trap", title: "Trap" },
      { id: "Vietnamese", title: "Vietnamese" },
      { id: "Webtoon", title: "Webtoon" },
      { id: "Webtoons", title: "Webtoons" },
      { id: "Yaoi", title: "Yaoi" },
      { id: "Yuri", title: "Yuri" },
      { id: "Zombie", title: "Zombie" },
    ],
  },
];

export type NiceoppaiSearchMetadata = {
  page?: number;
};
